### ISSUE TITLE
Error executing lua callback ... invalid key

### ISSUE THREAD

**Issue by olimorris** [willothy/veil.nvim#1]
With the following `minimal.lua` file:

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- Set stdpaths to use root dir
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- Bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {
  {
    "willothy/veil.nvim",
    config = true
  },
  -- Put any other plugins here
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

I get the following error:

```
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: .../.dotfiles/.repro/plugins/veil.nvim/lua/veil/section.lua:101: invalid key:
stack traceback:
        [C]: in function 'nvim_set_hl'
        .../.dotfiles/.repro/plugins/veil.nvim/lua/veil/section.lua:101: in function 'render'
        /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:113: in function 'redraw'
        /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:55: in function 'display'
        /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:180: in function </Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:178>
```

when I run `nvim --clean -u minimal.lua`

**Comment by willothy** [comment]
Try adding 

```lua
lazy = true,
event = 'VimEnter'
```

to the config. That fixes it for me - I'll look into that though, shouldn't be happening either way.

**Comment by olimorris** [comment]
Really odd, even with:

```lua
{
    "willothy/veil.nvim",
    config = true,
    lazy = true,
    event = "VimEnter"
}
```

or:

```lua
{
    "willothy/veil.nvim",
    config = true,
    event = "VimEnter"
}
```

I can't see a dashboard.

**Comment by willothy** [comment]
What neovim version are you using? I'm on nightly at the moment.

**Comment by olimorris** [comment]
Yep me too - `NVIM v0.9.0-dev-410dc33`

**Comment by willothy** [comment]
Ok found the cause, working on a fix now.

**Comment by willothy** [comment]
Should be fixed!

**Comment by olimorris** [comment]
Ahhhh I'm now getting:

```
Error executing lua callback: /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:137: Invalid 'line': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:137: in function 'redraw'
        /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:55: in function 'display'
        /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:180: in function </Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:178>
```

**Comment by willothy** [comment]
Lol! I'll look into that next

**Comment by willothy** [comment]
> Ahhhh I'm now getting:
> 
> ```
> Error executing lua callback: /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:137: Invalid 'line': out of range
> stack traceback:
>         [C]: in function 'nvim_buf_set_extmark'
>         /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:137: in function 'redraw'
>         /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:55: in function 'display'
>         /Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:180: in function </Users/Oli/.dotfiles/.repro/plugins/veil.nvim/lua/veil.lua:178>
> ```

Hmm, I can't reproduce this even with a minimal config. Are you loading any other plugins when you get that error?

The only context I know of for that error is when the screen is too small - that's an issue I'm working on fixing.

**Comment by olimorris** [comment]
Ahhh that was it! Plugging it into my monitor sorted it.

I'll raise the issue separately.
