### ISSUE TITLE
How can I change the Neovim text?

### ISSUE THREAD

**Issue by totordev** [willothy/veil.nvim#15]
Hello, I was working on my Neovim config and I was wondering: is there a way to change the Neovim text ? If yes, please tell me.

**Comment by willothy** [comment]
> Hello, I was working on my Neovim config and I was wondering: is there a way to change the Neovim text ? If yes, please tell me.

There is, you can create your own instances of `builtin.sections.animated`, but per the readme I would not recommend using this plugin right now. It is quite buggy and I am planning to rewrite all of it, and I will not be updating the current version. Check out alpha-nvim, it's much more user-friendly.

**Comment by totordev** [comment]
ok, thanks for the info! I'll definitely check alpha-nvim out.
